name: Daily Update

on:
  schedule:
    - cron: '49 21 * * *'
  workflow_dispatch:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整的提交历史，以便进行rebase

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Python script
      run: python main.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        
        # 检查是否有文件被修改
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update live files"
          
          # 拉取远程更新并rebase到当前分支
          git pull --rebase origin main
          
          # 推送更新
          git push origin main
        fi

    env:
      TZ: Asia/Shanghai
